# Generated by Django 2.0.5 on 2018-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_city',
            field=models.CharField(default=None, max_length=48, null=True, verbose_name='Город/Дом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_index',
            field=models.IntegerField(default=None, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=None, max_length=80, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=None, max_length=48, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_region',
            field=models.CharField(default=None, max_length=60, null=True, verbose_name='Регион/Область'),
        ),
    ]
